#!/usr/bin/env bash

sudo yum -y groupinstall "Development Tools"
sudo yum -y install gcc-c++ patch readline readline-devel zlib zlib-devel \
   libyaml-devel libffi-devel openssl-devel make \
   bzip2 autoconf automake libtool bison iconv-devel sqlite-devel
curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm reload
rvm install 2.6
rvm use 2.6 --default
sudo mkdir -p /opt/apps/
cd /opt/apps/
git clone https://github.com/rea-cruitment/simple-sinatra-app.git
cd /opt/apps/simple-sinatra-app
bundle install
bundle exec rackup -o 0.0.0.0 -p 80 &
